; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -Wall
; -wall tells the compiler to show all warnings, which can help identify potential issues in the code.
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306